<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm9-Temas.aspx.cs" Inherits="WebApplication1.WebForm9" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        TEMAS DE LA CATEGORIA<br />
        <br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="id_tema" DataSourceID="SqlDataSource1" OnSelectedIndexChanged="GridView1_SelectedIndexChanged1">
            <Columns>
                <asp:CommandField ShowSelectButton="True" />
                <asp:BoundField DataField="id_tema" HeaderText="id_tema" InsertVisible="False" ReadOnly="True" SortExpression="id_tema" />
                <asp:BoundField DataField="id_usuario" HeaderText="id_usuario" SortExpression="id_usuario" />
                <asp:BoundField DataField="nombre" HeaderText="nombre" SortExpression="nombre" />
                <asp:BoundField DataField="descripcion" HeaderText="descripcion" SortExpression="descripcion" />
                <asp:BoundField DataField="mensaje" HeaderText="mensaje" SortExpression="mensaje" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:TareaBDConnectionString %>" SelectCommand="SELECT [id_tema], [id_usuario], [nombre], [descripcion], [mensaje] FROM [Tema] WHERE ([id_categoria] = @id_categoria)" DeleteCommand="DELETE FROM Tema WHERE (id_tema = @id_tema) AND @volver=2 OR (id_tema = @id_tema) OR @volver=3 ">
            <DeleteParameters>
                <asp:SessionParameter Name="volver" SessionField="Volver" />
                <asp:SessionParameter Name="id_tema" SessionField="id_tema" />
            </DeleteParameters>
            <SelectParameters>
                <asp:SessionParameter Name="id_categoria" SessionField="id_categoria" Type="Int32" />
            </SelectParameters>
        </asp:SqlDataSource>
        <br />
        <asp:Button ID="Button1" runat="server" Height="30px" Text="Nuevo Tema" Width="84px" OnClick="Button1_Click" />
&nbsp;&nbsp;&nbsp;
        <asp:Button ID="Button2" runat="server" Height="30px" OnClick="Button2_Click" Text="Volver" Width="84px" />
        <br />
    
        <br />
    
    </div>
    </form>
</body>
</html>
