<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm10-Comentarios.aspx.cs" Inherits="WebApplication1.WebForm10_Comentarios" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        Mensajes del Tema<br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource1">
            <Columns>
                <asp:BoundField DataField="mensaje" HeaderText="mensaje" SortExpression="mensaje" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:TareaBDConnectionString %>" SelectCommand="SELECT [mensaje] FROM [Comentario] WHERE ([id_tema] = @id_tema)">
            <SelectParameters>
                <asp:SessionParameter Name="id_tema" SessionField="id_tema" Type="Int32" />
            </SelectParameters>
        </asp:SqlDataSource>
    
        <br />
        Comentario mas los contenidos de este:<br />
        <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id_comentario" DataSourceID="SqlDataSource2">
            <Columns>
                <asp:BoundField DataField="mensaje" HeaderText="mensaje" SortExpression="mensaje" />
                <asp:BoundField DataField="nombre" HeaderText="nombre" SortExpression="nombre" />
                <asp:BoundField DataField="avatar_url" HeaderText="avatar_url" SortExpression="avatar_url" />
                <asp:BoundField DataField="id_comentario" HeaderText="id_comentario" InsertVisible="False" ReadOnly="True" SortExpression="id_comentario" />
                <asp:BoundField DataField="id_usuario" HeaderText="id_usuario" SortExpression="id_usuario" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:TareaBDConnectionString %>" DeleteCommand="DELETE FROM Comentario WHERE (id_comentario = @id_comentario) AND (id_usuario = @id_usuariolog) OR (id_comentario = @id_comentario) AND (@id_grupolog = 2)" SelectCommand="SELECT Comentario.mensaje, Usuario.nombre, Usuario.avatar_url, Comentario.id_comentario, Comentario.id_usuario FROM Comentario INNER JOIN Usuario ON Comentario.id_usuario = Usuario.id_usuario AND Comentario.id_usuario = Usuario.id_usuario WHERE (Comentario.id_tema = @id_tema)" UpdateCommand="UPDATE Comentario SET mensaje = @mensaje WHERE id_comentario=@id_comentario AND id_usuario=@id_usuario">
            <DeleteParameters>
                <asp:SessionParameter Name="id_comentario" SessionField="id_comentario" />
                <asp:SessionParameter Name="id_usuariolog" SessionField="id_usuario" />
                <asp:SessionParameter Name="id_grupolog" SessionField="Volver" />
            </DeleteParameters>
            <SelectParameters>
                <asp:SessionParameter Name="id_tema" SessionField="id_tema" />
            </SelectParameters>
            <UpdateParameters>
                <asp:SessionParameter Name="id_comentario" SessionField="id_comentario" />
                <asp:SessionParameter Name="id_usuario" SessionField="id_usuario" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        <asp:TextBox ID="TextBox1" runat="server" Width="440px"></asp:TextBox>
&nbsp;&nbsp;&nbsp;
        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Comentar" Width="82px" />
        <br />
        <br />
        <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Volver" Width="75px" />
        <br />
    
    </div>
    </form>
</body>
</html>
